name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install ReportGenerator tool
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: >
        dotnet test ./test/AlgosAndDataStructures.UnitTest/AlgosAndDataStructures.UnitTest.csproj
        --no-build
        /p:CollectCoverage=true
        /p:CoverletOutput=./TestResults/coverage/
        /p:CoverletOutputFormat=cobertura

    - name: Generate coverage report
      run: >
        reportgenerator
        -reports:./test/**/TestResults/**/coverage.cobertura.xml
        -targetdir:coveragereport
        -reporttypes:HtmlInline;Badges

    - name: Upload badge artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: coveragereport/badges/badge.svg
