name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --collect "XPlat Code Coverage"
    - name: Publish results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./**/coverage.cobertura.xml
